# Generated by Django 4.2.8 on 2024-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable', models.ImageField(upload_to='uploads/')),
                ('class_name_table', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddTimeTable',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='class_name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
